services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "81:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env.docker
    networks:
      - internal
      - external
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - internal
      - external
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
      - external
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  external:
    name: external_network
    driver: bridge

volumes:
  postgres_data: